# Generated by Django 3.2.6 on 2021-09-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('avatar', models.TextField()),
                ('introduction', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_count', models.IntegerField(default=1)),
                ('floor', models.IntegerField()),
                ('img', models.TextField(default=None, null=True)),
                ('info', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('introduction', models.CharField(default='签名是一种态度，我想我可以更酷...', max_length=500)),
                ('sex', models.CharField(choices=[('m', '男'), ('w', '女'), ('u', '未知')], default='u', max_length=2)),
                ('avatar', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('info', models.TextField(null=True)),
                ('img', models.TextField(default=None, null=True)),
                ('floor_num', models.IntegerField(default=1)),
                ('ba', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Model.ba')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.user')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.floor')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.user')),
            ],
        ),
        migrations.AddField(
            model_name='floor',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.user'),
        ),
        migrations.AddField(
            model_name='floor',
            name='tie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.tie'),
        ),
        migrations.CreateModel(
            name='TieLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField()),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.user')),
                ('tie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.tie')),
            ],
            options={
                'unique_together': {('poster', 'tie')},
            },
        ),
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.user')),
                ('ba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.ba')),
            ],
            options={
                'unique_together': {('account', 'date', 'ba')},
            },
        ),
        migrations.CreateModel(
            name='ReplyFloorLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField()),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.user')),
                ('reply_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.replyfloor')),
            ],
            options={
                'unique_together': {('poster', 'reply_floor')},
            },
        ),
        migrations.CreateModel(
            name='FloorLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.floor')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.user')),
            ],
            options={
                'unique_together': {('poster', 'floor')},
            },
        ),
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.IntegerField(default=0)),
                ('subscription', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Model.user')),
                ('ba', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Model.ba')),
            ],
            options={
                'unique_together': {('account', 'ba')},
            },
        ),
    ]
