# Generated by Django 3.2.6 on 2021-09-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exp',
            old_name='exp',
            new_name='num',
        ),
    ]
