# Generated by Django 3.2.6 on 2021-09-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_rename_exp_exp_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('m', '男'), ('w', '女'), ('u', '未知')], default='未知', max_length=2),
        ),
    ]
