# Generated by Django 3.2.6 on 2021-09-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.BooleanField(db_index=True),
        ),
    ]
