# Generated by Django 3.2.6 on 2021-09-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0006_alter_like_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女'), ('3', '未知')], default='未知', max_length=2),
        ),
    ]
