# Generated by Django 3.2.6 on 2021-09-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0008_alter_like_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='target_type',
            field=models.CharField(choices=[('tie', 'Tie'), ('floor', 'Floor'), ('reply', 'Reply')], max_length=5),
        ),
    ]
