# Generated by Django 3.2.6 on 2021-09-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0009_alter_like_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('男', 'Male'), ('女', 'Female'), ('未知', 'Unknown')], default='未知', max_length=2),
        ),
    ]
