# Generated by Django 3.2.6 on 2021-10-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0011_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tie',
            name='ba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Model.ba'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(default='/media/images/null_user_avatar.jpg'),
        ),
    ]
